version: '3.4'
services:
  db:
    image: "postgres"
    container_name: currency-converter-db
    environment:
      - POSTGRES_DB=currencyconverter
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    expose:
      - 5432